### ISSUE TITLE
Add instructions on how to cite the handbook 

### ISSUE THREAD

**Issue by vtraag** [PathOS-project/indicator_handbook#29]
We should clarify how the handbook should be cited. Presumably this should be included in an introduction somewhere.

**Comment by tklebel** [comment]
I think it might be beneficial to add this information to every indicator template, since people might follow a link to a particular page, skipping the introduction.

In principle, it should be possible to auto-generate these based on the authors and title of each subchapter, but I'm not sure about the technical details of adding this to the pages themselves.

**Comment by vtraag** [comment]
Duplicate of #38 , I've decided to only include one citation in the introduction. We can revisit this choice if needed.

**Comment by vtraag** [comment]
Did decide to include citation separately as suggested in quarto (https://quarto.org/docs/authoring/create-citeable-articles.html), also to ensure that bibliographic information can be easily parsed, see 6fe7c5b40d382bddd4b208349b9a90a3363835f2
